const { spawn } = require('node:child_process');
const { once } = require('node:events');
const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '../..');

(async () => {
  const server = spawn(process.env.PYTHON || 'python', ['tests/integration.py', '--serve'], { cwd: root, stdio: ['pipe', 'pipe', 'inherit'] });
  let browser;
  const deadline = setTimeout(() => { server.kill(); throw new Error('Browser test timed out'); }, 120000);
  try {
    const line = readline.createInterface({ input: server.stdout });
    const info = await new Promise((resolve, reject) => {
      line.on('line', text => { if (text.startsWith('{')) resolve(JSON.parse(text)); });
      server.on('exit', code => reject(new Error('Fixture exited ' + code)));
    });
    browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}) });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(info.base);
    await page.locator('#login-form input').fill(info.password);
    await page.locator('#login-form button').click();
    await page.locator('#stat-down').filter({hasText:'KB'}).waitFor();
    await page.locator('#remove-by-status').click();
    assert(await page.locator('#remove-status-form [type=submit]').isDisabled());
    await page.locator('#remove-status-form [value=complete]').check();
    assert(await page.locator('#remove-status-form [type=submit]').isEnabled());
    assert(await page.locator('#remove-status-warning').isHidden());
    await page.locator('#remove-status-form [value=active]').check();
    assert(await page.locator('#remove-status-warning').isVisible());
    await page.locator('#cancel-remove-status').click();

    await require('./modal-drag.cjs')(page);
    await page.locator('#global-options').click();
    await page.locator('#options-form [name=max-overall-upload-limit]').fill('256K');
    assert.equal(await page.locator('#options-form [name=max-upload-limit]').count(),0);
    const limitRequest=page.waitForRequest(r=>r.url().endsWith('/api/options')&&r.method()==='POST');
    await page.locator('#options-form [type=submit]').click();
    assert.equal((await limitRequest).postDataJSON().options['max-overall-upload-limit'],'256K');
    await page.locator('#options-form').waitFor({state:'hidden'});
    await page.locator('#quick-add').click();
    assert.equal(await page.locator('#add-form input[name=directory]').getAttribute('placeholder'),'/downloads');
    await page.locator('#add-form input[name=directory]').fill('/downloads/历史');
    await page.locator('#add-form textarea').fill(info.fixture + '/file-ui.bin');
    await page.locator('#add-form button[type=submit]').click();
    await page.locator('.task-name').filter({hasText:'file-ui.bin'}).waitFor();
    fs.mkdirSync(path.join(root, 'artifacts/screenshots'), { recursive: true });
    await page.screenshot({ path: path.join(root, 'artifacts/screenshots/desktop-light.png'), fullPage: true });
    await page.locator('[data-action=pause]').first().click();
    await page.locator('.badge.paused').waitFor();
    await page.locator('nav a[data-page=subscriptions]').click();
    await page.locator('#new-sub').click();
    assert.equal(await page.locator('#sub-form input[name=skipExisting]').isChecked(),false);
    const includeBox=await page.locator('#sub-form input[name=filter]').boundingBox();
    const excludeBox=await page.locator('#sub-form input[name=excludeFilter]').boundingBox();
    assert.equal(includeBox.y,excludeBox.y,'Keyword inputs should align');
    assert.equal(includeBox.height,excludeBox.height);
    const regexButton=page.locator('#sub-form [data-regex=isFilterRegex]');
    await regexButton.scrollIntoViewIfNeeded();
    const beforeHover=await regexButton.boundingBox();
    await regexButton.hover();
    await page.waitForTimeout(200);
    const afterHover=await regexButton.boundingBox();
    assert.equal(afterHover.y,beforeHover.y,'Regex hover must not move the button');

    await page.locator('#sub-form input[name=name]').fill('浏览器订阅测试');
    await page.locator('#sub-form input[name=url]').fill(info.fixture + '/feed');
    assert.equal(await page.locator('#sub-form input[name=directory]').inputValue(),'/downloads/历史');
    assert.equal(await page.locator('#sub-form datalist option').first().getAttribute('value'),'/downloads/历史');
    assert.equal(await page.locator('#sub-form [data-directory-default]').count(),0);
    await page.locator('#sub-form input[name=namePath]').fill('作品:测试');
    await page.locator('#sub-form input[name=season]').fill('2');
    await page.locator('#sub-form input[name=autoDir]').check();
    await page.locator('#sub-form input[name=enabled]').uncheck();
    await page.locator('#sub-form input[name=excludeFilter]').fill('1080p');
    assert.equal(await page.locator('[data-final-directory]').textContent(),'/downloads/历史/作品_测试/{AI 识别的作品名}/Season 2');
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'忽略');
    await page.locator('#feed-preview [data-back]').click();
    assert.equal(await page.locator('#sub-form input[name=enabled]').isChecked(),false);
    assert.equal(await page.locator('#sub-form input[name=autoDir]').isChecked(),true);
    await page.locator('#sub-form input[name=filter]').fill('1080p');
    await page.locator('#sub-form input[name=excludeFilter]').fill('1080.');
    await page.locator('#sub-form [data-regex=isFilterRegex]').click();
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'匹配');
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#sub-form [data-regex=isFilterRegex]').click();
    await page.locator('#sub-form [data-regex=isExcludeFilterRegex]').click();
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'忽略');
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#sub-form input[name=autoDir]').uncheck();
    await page.locator('#sub-form input[name=excludeFilter]').fill('');
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#sub-form input[name=directory]').inputValue(),'/downloads/历史');
    await page.locator('#sub-form button[type=submit]').click();
    await page.locator('.sub-card').waitFor();
    await page.locator('[data-edit]').first().click();
    assert.equal(await page.locator('[data-regex=isFilterRegex]').getAttribute('aria-pressed'),'false');
    assert.equal(await page.locator('[data-regex=isExcludeFilterRegex]').getAttribute('aria-pressed'),'true');
    await page.keyboard.press('Escape');
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('.sub-more').first().locator('summary').click();
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), true);
    await page.locator('#content h1').first().click();
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), false);
    await page.locator('.sub-more').first().locator('summary').click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), false);
    const actionSizes=await page.locator('.sub-actions').first().evaluate(el=>[el.querySelector('[data-edit]'),el.querySelector('summary')].map(x=>({height:x.getBoundingClientRect().height,width:x.getBoundingClientRect().width})));
    assert.deepEqual(actionSizes[0],actionSizes[1]);
    await page.locator('.sub-more').first().locator('summary').click();
    await page.locator('[data-redownload]').first().click();
    await page.getByText('检查完成：提交 1 个任务，首次跳过 0 条',{exact:true}).waitFor();
    await page.locator('.sub-more').first().locator('summary').click();
    await page.locator('[data-history]').first().click();
    await page.getByText(/已提交下载/).first().waitFor();
    await page.locator('#modal-close').click();
    await page.locator('#new-sub').click();
    await page.locator('#sub-form input[name=name]').fill('立即下载测试');
    await page.locator('#sub-form input[name=url]').fill(info.fixture+'/feed?immediate=1');
    const checked=page.waitForResponse(r=>r.url().endsWith('/api/subscriptions/check')&&r.request().method()==='POST');
    await page.locator('#sub-form button[type=submit]').click();
    assert.equal((await (await checked).json()).submitted,1);
    await page.locator('.sub-card').filter({hasText:'立即下载测试'}).waitFor();
    await page.locator('nav a[data-page=anime]').click();
    await page.locator('.anime-card').first().waitFor();
    await page.locator('.hot.purple').waitFor();
    assert.equal(await page.locator('.anime-episode').first().textContent(),'第 7 集');
    assert.equal(await page.locator('.anime-card small').count(),0);
    await require('./modal-scroll.cjs')(page);
    const titleGeometry=await page.locator('.anime-card h3').evaluateAll(items=>items.map(x=>({height:x.getBoundingClientRect().height,line:Number.parseFloat(getComputedStyle(x).lineHeight),clamp:getComputedStyle(x).webkitLineClamp})));
    assert(titleGeometry.every(x=>Math.abs(x.height-2*x.line)<1&&x.clamp==='2'));
    assert.equal(await page.locator('.anime-card').count(), 3);
    assert.equal(await page.locator('.anime-card.unpublished[data-anime]:enabled').count(), 2);
    assert.deepEqual(await page.locator('.anime-day-heading h2').allTextContents(), ['星期一','星期三','星期日']);
    await page.locator('[data-day="星期三"]').click();
    assert.equal(await page.locator('.anime-card').count(), 1);
    assert.equal(await page.locator('.anime-card').isDisabled(), false);
    await page.route('**/api/anime/456/review',route=>route.fulfill({json:{score:null,review:'待发布番剧评析',createdAt:new Date().toISOString()}}));
    await page.locator('.anime-card').click();
    await page.locator('#modal-title').filter({hasText:'周三待发布'}).waitFor();
    assert.equal(await page.locator('#anime-summary').textContent(),'源站暂未提供该番剧的简介。');
    assert.match(await page.locator('#anime-groups-empty').textContent(),/暂无字幕组发布/);
    assert.equal(await page.locator('#modal-body [data-sub], #modal-body [data-feed]').count(),0);
    assert.equal((await page.locator('#modal-body').textContent()).includes('全部字幕组'),false);
    await page.waitForFunction(()=>!document.querySelector('#ai-review').disabled);
    assert.equal(await page.locator('#translate-summary').isEnabled(),false);
    await page.locator('#ai-review').click();
    await page.locator('#ai-review-content').filter({hasText:'待发布番剧评析'}).waitFor();
    await page.locator('#modal-close').click();
    await page.unroute('**/api/anime/456/review');

    await page.locator('[data-day="全部"]').click();
    await page.locator('#anime-search').fill('周日待发布');
    assert.equal(await page.locator('.anime-card').count(), 1);
    assert.deepEqual(await page.locator('.anime-day-heading h2').allTextContents(), ['星期日']);
    await page.locator('.anime-card').click();
    await page.locator('#modal-title').filter({hasText:'周日待发布 & 新番'}).waitFor();
    assert.equal(await page.locator('#anime-summary').textContent(),'尚未发布作品的真实简介。');
    assert.equal(await page.locator('#translate-summary').isEnabled(),true);
    assert.equal(await page.locator('#anime-groups-empty').count(),1);
    assert.equal(await page.locator('#modal-body [data-sub], #modal-body [data-feed]').count(),0);
    await page.screenshot({path:path.join(root,'artifacts/screenshots/anime-unpublished-detail.png')});
    await page.locator('#modal-close').click();
    await page.locator('#anime-search').fill('');
    await page.screenshot({path:path.join(root,'artifacts/screenshots/anime-weekday-groups.png'),fullPage:true});
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('[data-sub]').first().waitFor();
    await require('./anime-review.cjs')(page);
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=settings]').click();
    await page.locator('[name=localBtPort]').fill('17888');
    await require('./desktop-settings.cjs')(page);
    await page.locator('[name=tuning-max-concurrent-downloads]').fill('2');
    await page.locator('[name=trackerAutoUpdate]').check();
    await page.locator('[name=trackerSources]').fill(info.fixture+'/trackers');
    await page.locator('#update-trackers').click();
    await page.locator('#tracker-status').filter({hasText:'缓存 2 个'}).waitFor();
    await page.reload();
    await page.locator('[name=localBtPort]').waitFor();
    assert.equal(await page.locator('[name=localBtPort]').inputValue(),'17888');
    assert.equal(await page.locator('[name=tuning-max-concurrent-downloads]').inputValue(),'2');
    await page.locator('#download').screenshot({path:path.join(root,'artifacts/screenshots/local-tuning.png')});
    await page.locator('#diagnose-local').click();
    await page.locator('#modal-body').filter({hasText:'公网连通性'}).waitFor();
    await page.locator('#modal-close').click();
    await page.locator('#theme-dark + .theme-card').click();
    assert.equal(await page.locator('#theme-dark').isChecked(), true);
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.locator('#theme-auto + .theme-card').click();
    assert.equal(await page.locator('#theme-auto').isChecked(), true);
    await page.emulateMedia({colorScheme:'dark'});
    await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.locator('#ai').scrollIntoViewIfNeeded();
    await page.locator('#new-ai').click();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture);
    await page.locator('#ai-form input[name=modelName]').fill('test-model');
    await page.locator('#ai-form input[name=apiKey]').fill('test-key');
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.ai-test-success').waitFor();
    assert.match(await page.locator('#ai-test-result').textContent(),/返回内容：/);
    const beforeSave=await page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
    assert.equal(beforeSave.settings.aiProfiles.length,0);
    await page.locator('#ai-form button[type=submit]').click();
    await page.locator('[data-edit-ai]').waitFor();
    await page.locator('[data-edit-ai]').click();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture+'/invalid');
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.error').waitFor();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture);
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.ai-test-success').waitFor();
    await page.locator('#ai-form input[name=name]').fill('编辑后的接口');
    await page.locator('#ai-form button[type=submit]').click();
    await page.getByText('编辑后的接口',{exact:true}).waitFor();
    assert.equal(await page.locator('select[name=selectedAiId]').count(),0);
    const secondAi=await page.evaluate(async fixture=>{
      const response=await fetch('/api/ai/profiles',{method:'POST',headers:{'Content-Type':'application/json','X-Aria2Fast':'1'},body:JSON.stringify({name:'备用模型',baseUrl:fixture,modelName:'second-model',apiKey:'test-key',protocol:'OpenAIChatCompletions'})});
      return response.json();
    },info.fixture);
    await page.reload();
    await page.locator('[name=subscriptionIntervalMinutes]').fill('27');
    await page.locator('[data-select-ai="'+secondAi.id+'"]').click();
    await page.locator('[data-select-ai="'+secondAi.id+'"][aria-pressed=true]').waitFor();
    assert.equal(await page.locator('[name=subscriptionIntervalMinutes]').inputValue(),'27');
    assert.equal(await page.evaluate(()=>fetch('/api/state').then(r=>r.json()).then(s=>s.settings.selectedAiId)),secondAi.id);
    await page.reload();
    await page.locator('[data-select-ai="'+secondAi.id+'"][aria-pressed=true]').waitFor();
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-delete-ai="'+secondAi.id+'"]').click();
    await page.locator('[data-select-ai][aria-pressed=true]').waitFor();

    await page.locator('nav a[data-page=anime]').click();
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('#translate-summary').click();
    await page.locator('#anime-summary').filter({hasText:'连接成功'}).waitFor();
    await page.locator('#modal-close').click();
    await page.reload();
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('#anime-summary').filter({hasText:'连接成功'}).waitFor();
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=settings]').click();
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-delete-ai]').click();
    await page.locator('#ai .empty-state').filter({hasText:'尚未配置 AI 接口'}).waitFor();
    await page.setViewportSize({width:390,height:844});
    for (const tab of ['downloads','subscriptions','anime','activity','settings']) {
      await page.locator('nav a[data-page=' + tab + ']').click();
      await page.waitForTimeout(400);
      await page.evaluate(() => { window.scrollTo(0,0); document.querySelector('#toasts').replaceChildren(); });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, 'overflow on '+tab);
      await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-'+tab+'.png'),fullPage:true});
    }
    await page.locator('#theme-light + .theme-card').click();
    await page.reload();
    await page.locator('#theme-light + .theme-card').waitFor();
    assert.equal(await page.locator('#theme-light').isChecked(), true);
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    await page.locator('#quick-add').click();
    assert.equal(await page.locator('#add-form datalist option').first().getAttribute('value'),'/downloads/历史');
    assert.equal(await page.locator('#add-form input[name=directory]').inputValue(),'/downloads/历史');
    await page.locator('#add-form select[name=nodeId]').selectOption('local');
    assert.equal(await page.locator('#add-form datalist option').count(),0);
    assert.equal(await page.locator('#add-form input[name=directory]').inputValue(),'');
    const placeholder=await page.locator('#add-form input[name=directory]').getAttribute('placeholder');
    assert(placeholder && placeholder!='/downloads');
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=subscriptions]').click();
    await page.locator('[data-edit]').first().click();
    assert.equal(await page.locator('[data-final-directory]').textContent(),'/downloads/历史/作品_测试/Season 2');
    await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-subscription-path.png'),fullPage:true});
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview').evaluate(x=>x.scrollWidth<=x.clientWidth+1),true);
    await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-subscription-preview.png'),fullPage:true});
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#modal-close').click();
    assert.deepEqual(errors, []);
    console.log('PASS browser: login, add/pause task, subscription preview/save, anime detail, AI configuration/test, mobile navigation/overflow, auto/manual theme persistence; no JS errors');
  } finally {
    clearTimeout(deadline);
    if(browser) await browser.close();
    server.stdin.end();
    await once(server,'exit').catch(()=>{});
  }
})().catch(error => { console.error(error); process.exitCode=1; });
