const { spawn } = require('node:child_process');
const { once } = require('node:events');
const fs = require('node:fs');
const path = require('node:path');
const readline = require('node:readline');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '../..');

(async () => {
  const server = spawn(process.env.PYTHON || 'python', ['tests/integration.py', '--serve'], { cwd: root, stdio: ['pipe', 'pipe', 'inherit'] });
  let browser;
  const deadline = setTimeout(() => { server.kill(); throw new Error('Browser test timed out'); }, 120000);
  try {
    const line = readline.createInterface({ input: server.stdout });
    const info = await new Promise((resolve, reject) => {
      line.on('line', text => { if (text.startsWith('{')) resolve(JSON.parse(text)); });
      server.on('exit', code => reject(new Error('Fixture exited ' + code)));
    });
    browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}) });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(info.base);
    await page.locator('#login-form input').fill(info.password);
    await page.locator('#login-form button').click();
    await page.locator('#stat-down').filter({hasText:'KB'}).waitFor();
    await require('./modal-drag.cjs')(page);
    await page.locator('#quick-add').click();
    assert.equal(await page.locator('#add-form input[name=directory]').getAttribute('placeholder'),'/downloads');
    await page.locator('#add-form input[name=directory]').fill('/downloads/历史');
    await page.locator('#add-form textarea').fill(info.fixture + '/file-ui.bin');
    await page.locator('#add-form button[type=submit]').click();
    await page.locator('.task-name').filter({hasText:'file-ui.bin'}).waitFor();
    fs.mkdirSync(path.join(root, 'artifacts/screenshots'), { recursive: true });
    await page.screenshot({ path: path.join(root, 'artifacts/screenshots/desktop-light.png'), fullPage: true });
    await page.locator('[data-action=pause]').first().click();
    await page.locator('.badge.paused').waitFor();
    await page.locator('nav a[data-page=subscriptions]').click();
    await page.locator('#new-sub').click();
    assert.equal(await page.locator('#sub-form input[name=skipExisting]').isChecked(),false);
    await page.locator('#sub-form input[name=name]').fill('浏览器订阅测试');
    await page.locator('#sub-form input[name=url]').fill(info.fixture + '/feed');
    assert.equal(await page.locator('#sub-form input[name=directory]').inputValue(),'/downloads/历史');
    assert.equal(await page.locator('#sub-form datalist option').first().getAttribute('value'),'/downloads/历史');
    assert.equal(await page.locator('#sub-form [data-directory-default]').count(),0);
    await page.locator('#sub-form input[name=namePath]').fill('作品:测试');
    await page.locator('#sub-form input[name=season]').fill('2');
    await page.locator('#sub-form input[name=autoDir]').check();
    await page.locator('#sub-form input[name=enabled]').uncheck();
    await page.locator('#sub-form input[name=excludeFilter]').fill('1080p');
    assert.equal(await page.locator('[data-final-directory]').textContent(),'/downloads/历史/作品_测试/{AI 识别的作品名}/Season 2');
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'忽略');
    await page.locator('#feed-preview [data-back]').click();
    assert.equal(await page.locator('#sub-form input[name=enabled]').isChecked(),false);
    assert.equal(await page.locator('#sub-form input[name=autoDir]').isChecked(),true);
    await page.locator('#sub-form input[name=filter]').fill('1080p');
    await page.locator('#sub-form input[name=excludeFilter]').fill('1080.');
    await page.locator('#sub-form [data-regex=isFilterRegex]').click();
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'匹配');
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#sub-form [data-regex=isFilterRegex]').click();
    await page.locator('#sub-form [data-regex=isExcludeFilterRegex]').click();
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview .badge').textContent(),'忽略');
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#sub-form input[name=autoDir]').uncheck();
    await page.locator('#sub-form input[name=excludeFilter]').fill('');
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#sub-form input[name=directory]').inputValue(),'/downloads/历史');
    await page.locator('#sub-form button[type=submit]').click();
    await page.locator('.sub-card').waitFor();
    await page.locator('[data-edit]').first().click();
    assert.equal(await page.locator('[data-regex=isFilterRegex]').getAttribute('aria-pressed'),'false');
    assert.equal(await page.locator('[data-regex=isExcludeFilterRegex]').getAttribute('aria-pressed'),'true');
    await page.keyboard.press('Escape');
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('.sub-more').first().locator('summary').click();
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), true);
    await page.locator('#content h1').first().click();
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), false);
    await page.locator('.sub-more').first().locator('summary').click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.sub-more').first().evaluate(menu => menu.open), false);
    const actionSizes=await page.locator('.sub-actions').first().evaluate(el=>[el.querySelector('[data-edit]'),el.querySelector('summary')].map(x=>({height:x.getBoundingClientRect().height,width:x.getBoundingClientRect().width})));
    assert.deepEqual(actionSizes[0],actionSizes[1]);
    await page.locator('.sub-more').first().locator('summary').click();
    await page.locator('[data-redownload]').first().click();
    await page.getByText('检查完成：提交 1 个任务，首次跳过 0 条',{exact:true}).waitFor();
    await page.locator('.sub-more').first().locator('summary').click();
    await page.locator('[data-history]').first().click();
    await page.getByText(/已提交下载/).first().waitFor();
    await page.locator('#modal-close').click();
    await page.locator('#new-sub').click();
    await page.locator('#sub-form input[name=name]').fill('立即下载测试');
    await page.locator('#sub-form input[name=url]').fill(info.fixture+'/feed?immediate=1');
    const checked=page.waitForResponse(r=>r.url().endsWith('/api/subscriptions/check')&&r.request().method()==='POST');
    await page.locator('#sub-form button[type=submit]').click();
    assert.equal((await (await checked).json()).submitted,1);
    await page.locator('.sub-card').filter({hasText:'立即下载测试'}).waitFor();
    await page.locator('nav a[data-page=anime]').click();
    await page.locator('.anime-card').first().waitFor();
    await page.locator('.hot.purple').waitFor();
    assert.equal(await page.locator('.anime-episode').first().textContent(),'第 7 集');
    assert.equal(await page.locator('.anime-card small').count(),0);
    await require('./modal-scroll.cjs')(page);
    const titleGeometry=await page.locator('.anime-card h3').evaluateAll(items=>items.map(x=>({height:x.getBoundingClientRect().height,line:Number.parseFloat(getComputedStyle(x).lineHeight),clamp:getComputedStyle(x).webkitLineClamp})));
    assert(titleGeometry.every(x=>Math.abs(x.height-2*x.line)<1&&x.clamp==='2'));
    assert.equal(await page.locator('.anime-card').count(), 3);
    assert.equal(await page.locator('.anime-card.unpublished:disabled').count(), 2);
    assert.deepEqual(await page.locator('.anime-day-heading h2').allTextContents(), ['星期一','星期三','星期日']);
    await page.locator('[data-day="星期三"]').click();
    assert.equal(await page.locator('.anime-card').count(), 1);
    assert.equal(await page.locator('.anime-card').isDisabled(), true);
    await page.locator('[data-day="全部"]').click();
    await page.locator('#anime-search').fill('周日待发布');
    assert.equal(await page.locator('.anime-card').count(), 1);
    assert.deepEqual(await page.locator('.anime-day-heading h2').allTextContents(), ['星期日']);
    await page.locator('#anime-search').fill('');
    await page.screenshot({path:path.join(root,'artifacts/screenshots/anime-weekday-groups.png'),fullPage:true});
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('[data-sub]').first().waitFor();
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=settings]').click();
    await page.locator('#theme-dark + .theme-card').click();
    assert.equal(await page.locator('#theme-dark').isChecked(), true);
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.locator('#theme-auto + .theme-card').click();
    assert.equal(await page.locator('#theme-auto').isChecked(), true);
    await page.emulateMedia({colorScheme:'dark'});
    await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    await page.locator('#ai').scrollIntoViewIfNeeded();
    await page.locator('#new-ai').click();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture);
    await page.locator('#ai-form input[name=modelName]').fill('test-model');
    await page.locator('#ai-form input[name=apiKey]').fill('test-key');
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.ai-test-success').waitFor();
    assert.match(await page.locator('#ai-test-result').textContent(),/返回内容：/);
    const beforeSave=await page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
    assert.equal(beforeSave.settings.aiProfiles.length,0);
    await page.locator('#ai-form button[type=submit]').click();
    await page.locator('[data-edit-ai]').waitFor();
    await page.locator('[data-edit-ai]').click();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture+'/invalid');
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.error').waitFor();
    await page.locator('#ai-form input[name=baseUrl]').fill(info.fixture);
    await page.locator('#test-ai').click();
    await page.locator('#ai-test-result.ai-test-success').waitFor();
    await page.locator('#ai-form input[name=name]').fill('编辑后的接口');
    await page.locator('#ai-form button[type=submit]').click();
    await page.getByText('编辑后的接口',{exact:true}).waitFor();
    await page.locator('nav a[data-page=anime]').click();
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('#translate-summary').click();
    await page.locator('#anime-summary').filter({hasText:'连接成功'}).waitFor();
    await page.locator('#modal-close').click();
    await page.reload();
    await page.locator('.anime-card[data-anime="123"]').click();
    await page.locator('#anime-summary').filter({hasText:'连接成功'}).waitFor();
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=settings]').click();
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-delete-ai]').click();
    await page.locator('#ai .empty-state').filter({hasText:'尚未配置 AI 接口'}).waitFor();
    await page.setViewportSize({width:390,height:844});
    for (const tab of ['downloads','subscriptions','anime','activity','settings']) {
      await page.locator('nav a[data-page=' + tab + ']').click();
      await page.waitForTimeout(400);
      await page.evaluate(() => { window.scrollTo(0,0); document.querySelector('#toasts').replaceChildren(); });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, 'overflow on '+tab);
      await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-'+tab+'.png'),fullPage:true});
    }
    await page.locator('#theme-light + .theme-card').click();
    await page.reload();
    await page.locator('#theme-light + .theme-card').waitFor();
    assert.equal(await page.locator('#theme-light').isChecked(), true);
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    await page.locator('#quick-add').click();
    assert.equal(await page.locator('#add-form datalist option').first().getAttribute('value'),'/downloads/历史');
    assert.equal(await page.locator('#add-form input[name=directory]').inputValue(),'/downloads/历史');
    await page.locator('#add-form select[name=nodeId]').selectOption('local');
    assert.equal(await page.locator('#add-form datalist option').count(),0);
    assert.equal(await page.locator('#add-form input[name=directory]').inputValue(),'');
    const placeholder=await page.locator('#add-form input[name=directory]').getAttribute('placeholder');
    assert(placeholder && placeholder!='/downloads');
    await page.locator('#modal-close').click();
    await page.locator('nav a[data-page=subscriptions]').click();
    await page.locator('[data-edit]').first().click();
    assert.equal(await page.locator('[data-final-directory]').textContent(),'/downloads/历史/作品_测试/Season 2');
    await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-subscription-path.png'),fullPage:true});
    await page.locator('#preview-sub').click();
    await page.locator('#feed-preview .file-row').waitFor();
    assert.equal(await page.locator('#feed-preview').evaluate(x=>x.scrollWidth<=x.clientWidth+1),true);
    await page.screenshot({path:path.join(root,'artifacts/screenshots/mobile-subscription-preview.png'),fullPage:true});
    await page.locator('#feed-preview [data-back]').click();
    await page.locator('#modal-close').click();
    assert.deepEqual(errors, []);
    console.log('PASS browser: login, add/pause task, subscription preview/save, anime detail, AI configuration/test, mobile navigation/overflow, auto/manual theme persistence; no JS errors');
  } finally {
    clearTimeout(deadline);
    if(browser) await browser.close();
    server.stdin.end();
    await once(server,'exit').catch(()=>{});
  }
})().catch(error => { console.error(error); process.exitCode=1; });
